# Generated by Django 4.0.3 on 2022-10-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='city',
            field=models.CharField(default='Mumbai', max_length=20),
        ),
    ]
